### PR TITLE
MOSIP-32782 - Password-protected file is not allowed for upload

### PR DESCRIPTION
**Pull request by GOKULRAJ136**

### CODE REVIEW

**Review by mayuradesh — CHANGES_REQUESTED** [review]
1. Remove handling for non PDF types
2. Move document.close() to finally block

**Comment by GOKULRAJ136** [comment]
> 1. Remove handling for non PDF types
> 2. Move document.close() to finally block

Removed the handling of non-PDF files and included document.close() in the finally block.

**Review by mayuradesh — CHANGES_REQUESTED** [review]
1. Internal server error is not allowed, it should be proper specific Error Code only
2. Try Catch and Finally needs cleanup
3. No use of document.isEncrypted
4. Check when to send true in all cases in the validation method

**Comment by GOKULRAJ136** [comment]
> 1. Internal server error is not allowed, it should be proper specific Error Code only
> 2. Try Catch and Finally needs cleanup
> 3. No use of document.isEncrypted
> 4. Check when to send true in all cases in the validation method

- Resolved an internal server error caused by the **DocumentException** we were using. By switching to a different exception, which is utilized in other methods, now successfully retrieved the accurate error code and message on the server side.
- Removed the unused document.isEncrypted() method and cleaned up the try-catch blocks.
- Returning 'true' in the event of an IOException could lead to the mistaken belief that the file is password-protected, when in fact, an error may be hindering the password verification, potentially causing false positives, so better to return a false in this case.

**Review by mayuradesh — CHANGES_REQUESTED** [review]
Instead of returning false on catching IOException, throw the IOException in isPasswordProtectedFile()

**Comment by GOKULRAJ136** [comment]
> Instead of returning false on catching IOException, throw the IOException in isPasswordProtectedFile()

Threw an IOException instead of catching it.

**Review by mayuradesh — APPROVED** [review]

**Pull request merged**
